<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="María Bustamante, Nicolás Jadán">

<title>SVM</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="SVM_Bustamante_Jadan_files/libs/clipboard/clipboard.min.js"></script>
<script src="SVM_Bustamante_Jadan_files/libs/quarto-html/quarto.js"></script>
<script src="SVM_Bustamante_Jadan_files/libs/quarto-html/popper.min.js"></script>
<script src="SVM_Bustamante_Jadan_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="SVM_Bustamante_Jadan_files/libs/quarto-html/anchor.min.js"></script>
<link href="SVM_Bustamante_Jadan_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="SVM_Bustamante_Jadan_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="SVM_Bustamante_Jadan_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="SVM_Bustamante_Jadan_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="SVM_Bustamante_Jadan_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">SVM</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>María Bustamante, Nicolás Jadán </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="svm" class="level1">
<h1>SVM</h1>
<section id="recopilar-datos-y-transformar" class="level2">
<h2 class="anchored" data-anchor-id="recopilar-datos-y-transformar">1. Recopilar datos y transformar</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>libraries <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"reshape2"</span>, <span class="st">"ggplot2"</span>, <span class="st">"kernlab"</span> ,<span class="st">"caret"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>check.libraries <span class="ot">&lt;-</span> <span class="fu">is.element</span>(libraries, <span class="fu">installed.packages</span>()[, <span class="dv">1</span>])<span class="sc">==</span><span class="cn">FALSE</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>libraries.to.install <span class="ot">&lt;-</span> libraries[check.libraries]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(libraries.to.install<span class="sc">!=</span><span class="dv">0</span>)) {</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(libraries.to.install)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>success <span class="ot">&lt;-</span> <span class="fu">sapply</span>(libraries,require, <span class="at">quietly =</span> <span class="cn">FALSE</span>,  <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: reshape2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: kernlab</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kernlab'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    alpha</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: caret</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">length</span>(success) <span class="sc">!=</span> <span class="fu">length</span>(libraries)) {<span class="fu">stop</span>(<span class="st">"A package failed to return a success in require() function."</span>)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Explicación:</strong></p>
<p>En esta sección se comprueba si las bibliotecas que se necesitan para esta tarea están instaladas y las instala automáticamente si no lo están. Después, comprueba si todas las bibliotecas se cargaron corectamente y muestra un mensaje de errores si alguna no se instaló bien.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>datos<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"./cancer.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Explicación:</strong></p>
<p>Se carga el conjunto de datos con el que se va a trabajar. Dicho conjunto de datos, consta de 31 variables, la primera es la clasificación del tumor (benigno o maligno), mientras que las variables restantes, son características de las células, producto de un procesado de imagen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">$</span>diagnostico <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(datos<span class="sc">$</span>diagnostico)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>clase <span class="ot">&lt;-</span> datos<span class="sc">$</span>diagnostico</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Explicación:</strong></p>
<p>En esta parte se convierte la variable categórica a factoe y se guarda en la misma variable para poder utilizarla en los siguientes pasos. En la segunda línea se extrae la columna de diagnóstico y se un objeto llamado clase.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Col<span class="ot">&lt;-</span><span class="fu">colnames</span>(datos)[<span class="dv">2</span><span class="sc">:</span><span class="dv">31</span>]</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span>datos[,Col]</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>X.melt<span class="ot">&lt;-</span><span class="fu">melt</span>((<span class="fu">log2</span>(X)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>No id variables; using all as measure variables</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>value,<span class="at">colour=</span>variable), <span class="at">data=</span>X.melt)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">show.legend =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 78 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="SVM_Bustamante_Jadan_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Explicación:</strong></p>
<ul>
<li><p><code>Col&lt;-colnames(datos)[2:31]</code>: En esta línea, se crea un nuevo vector (col) que abarca las columnas desde la posición 2 hasta la 31.</p></li>
<li><p><code>X&lt;-datos[,Col</code>]: Se crea un nuevo objetoo que contiene todas las filas y solo las columnas especificadas en el vector <strong><code>Col</code></strong> del objeto de datos.</p></li>
<li><p><code>X.melt&lt;-melt((log2(X))):</code> Melt se usa para transformar el objeto X en un formato largo o longitudinal. También se aplica la función <strong><code>log2()</code></strong> a los valores de <strong><code>X</code></strong> antes de la transformación. Con la función <strong><code>melt()</code></strong> se facilita el uso de los datos en visualizaciones posteriores.</p></li>
<li><p><code>p &lt;- ggplot(aes(x=value,colour=variable), data=X.melt)</code>: En esta línea, se crea un objeto ggplot llamado p.&nbsp;Se especifica que el eje x del gráfico estará representado por la columna value en el objeto X.melt, y el color de las líneas de densidad se basará en la columna variable en X.melt.</p></li>
<li><p><code>p + geom_density(show.legend = F)</code>: Finalmente, se agrega una capa de densidad al gráfico p utilizando geom_density(). Esto generará las líneas de densidad en el gráfico. El argumento show.legend = F se utiliza para evitar que se muestre la leyenda en el gráfico.</p></li>
<li><p>Gráfica: Las curvas de densidad representan la distribución de valores para una variable en específico. Las variables de cada curva se identifican por el color de la curva. Al trazar las curvas de densidad, se puede visualizar la distribución y la forma de las variables seleccionadas. Las áreas más altas y anchas indican una mayor concentración de valores en esas áreas. Por el contrario, los rangos más bajos y más estrechos indican una menor concentración de valores.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>X.log<span class="ot">&lt;-</span><span class="fu">log2</span>(X)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>datos.log<span class="ot">&lt;-</span><span class="fu">cbind</span>(X,clase)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(datos.log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div>
<p><strong>Explicación:</strong></p>
<ul>
<li><p><code>X.log&lt;-log2(X):</code> Se aplica la función log2() a la matriz de datos X para calcular el logaritmo base 2 de cada valor en X. Esto se hace para transformar los valores de X utilizando el logaritmo.</p></li>
<li><p><code>datos.log &lt;- cbind(X, clase):</code>cbind se usa para combinar las columnas de X y clase en un solo objeto de datos, en donde X tiene las variables de entrada mientras que clase contiene las de salida corrspondiente a cada observación. En resumen en “datos.log”, “X.log” se ubicará en las primeras columnas, seguido por la columna “clase”.</p></li>
<li><p><code>class(datos.log):</code> se devuelve la clse de ‘datos.log’.</p></li>
</ul>
</section>
<section id="división-de-datos-para-entrenamiento-y-prueba" class="level2">
<h2 class="anchored" data-anchor-id="división-de-datos-para-entrenamiento-y-prueba">2. División de datos para entrenamiento y prueba</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>datos2<span class="ot">&lt;-</span><span class="fu">colnames</span>(datos[<span class="dv">1</span><span class="sc">:</span><span class="dv">31</span>])</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>datos2<span class="ot">&lt;-</span>datos[,datos2]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">$</span>diagnostico<span class="ot">&lt;-</span><span class="fu">as.factor</span>(datos2<span class="sc">$</span>diagnostico)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Explicación:</strong></p>
<p>En este código se crea un vector de datos que contiene las columnas desde la 1 a la 31, haciendo uso de la función colnames. Luego, se convierte la columna “diagnostico” del objetodatos en un factor utilizando la columna correspondiente en datos2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123456</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>datos2[,<span class="dv">2</span><span class="sc">:</span><span class="dv">31</span>]<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(<span class="fu">scale</span>(datos2[,<span class="dv">2</span><span class="sc">:</span><span class="dv">31</span>]))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(datos2)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"B"</span>,<span class="st">"M"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>entrenamiento<span class="ot">&lt;-</span><span class="fu">sample</span>(<span class="fu">nrow</span>(datos2),<span class="at">size=</span><span class="fu">nrow</span>(datos2)<span class="sc">*</span><span class="fl">0.7</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>entrenamiento.data<span class="ot">&lt;-</span>datos2[entrenamiento,]</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>prueba.data<span class="ot">&lt;-</span>datos2[<span class="sc">-</span>entrenamiento,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Explicación:</strong></p>
<ul>
<li><p><code>set.seed(123456)</code>: Se fija la semilla para asegurar que los resultados sean los mismos cada vez que se ejecute el código.</p></li>
<li><p><code>datos2[,2:31]</code>: La función scale() realiza una estandarización, lo que significa que centra los valores alrededor de su media y los escala por su desviación estándar. La función as.data.frame() se utiliza para convertir los resultados de la estandarización nuevamente en un objeto de datos.</p></li>
<li><p><code>levels(datos2)&lt;-c("B","M"):</code> Se establecen los niveles de la variable de interés siendo Benigno (B) y Maligno (M).</p></li>
<li><p>Finalmente se dividen los datos en 70% para entrenamiento y 30% para prueba.</p></li>
</ul>
</section>
<section id="entrenamiento-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="entrenamiento-del-modelo">3. Entrenamiento del modelo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>clasifier.lineal <span class="ot">&lt;-</span> <span class="fu">ksvm</span>(diagnostico <span class="sc">~</span> ., <span class="at">data =</span> entrenamiento.data, <span class="at">kernel =</span> <span class="st">"vanilladot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Setting default kernel parameters  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>clasifier.gauss <span class="ot">&lt;-</span> <span class="fu">ksvm</span>(diagnostico <span class="sc">~</span> ., <span class="at">data =</span> entrenamiento.data, <span class="at">kernel =</span> <span class="st">"rbfdot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Explicación:</strong></p>
<p>Este código realiza dos clasificadores tilizando el algoritmo de SVM con diferentes kernels.</p>
<ul>
<li><p><code>clasifier.lineal</code>: En esta línea, se crea un clasificador SVM lineal utilizando la función ksvm() . El argumento diagnostico ~ . especifica que se utiliza la columna diagnostico como variable objetivo y todas las demás columnas del objeto de datos entrenamiento.data como variables predictoras. El kernel utilizado es “vanilladot”, que es un kernel lineal.</p></li>
<li><p><code>clasifier.gauss</code>: En esta línea, se crea otro clasificador SVM utilizando la misma estructura que en el paso anterior, pero con un kernel diferente. En este caso, se utiliza el kernel “rbfdot”, que es un kernel gaussiano</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>clasifier.lineal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Support Vector Machine object of class "ksvm" 

SV type: C-svc  (classification) 
 parameter : cost C = 1 

Linear (vanilla) kernel function. 

Number of Support Vectors : 33 

Objective Function Value : -21.2999 
Training error : 0.012563 </code></pre>
</div>
</div>
<p><strong>Explicación:</strong></p>
<ul>
<li><p>C-svc significa que se está utilizando un SVM de clasificación con función de costo. El parámetro C=1 es un factor de regularización que controla la penalización por clasificar incorrectamente puntos de datos en el algoritmo. En este caso indica un factor de regularización moderado.</p></li>
<li><p>linear (vanilla): El kernel lineal es una función que permite realizar la clasificación en un espacio de características lineal.</p></li>
<li><p>Número de Vectores de Soporte (33): Indica el número de vectores de soporte encontrados durante el entrenamiento del modelo. Los vectores de soporte son los puntos de datos que influyen en la definición del hiperplano de separación entre las clases.</p></li>
<li><p>Valor de la Función Objetivo (-21.2999): Este valor representa la función objetivo del modelo SVM. En general, se busca minimizar esta función durante el entrenamiento del modelo.</p></li>
<li><p>Error de entrenamiento ( 0.012563): Este valor indica el error de entrenamiento del modelo SVM, es decir, el porcentaje de puntos de datos de entrenamiento que se clasificaron incorrectamente. En este caso, el error de entrenamiento es del 1.26%.</p></li>
</ul>
<p>En conclusión el valor de la función objetivo del modelo es de -21.2999 y el error de entrenamiento obtenido es de 0.012563, lo que muestra que el modelo ha logrado una buena capacidad de clasificación en los datos de entrenamiento.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>clasifier.gauss</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Support Vector Machine object of class "ksvm" 

SV type: C-svc  (classification) 
 parameter : cost C = 1 

Gaussian Radial Basis kernel function. 
 Hyperparameter : sigma =  0.0405393061667693 

Number of Support Vectors : 107 

Objective Function Value : -47.3373 
Training error : 0.015075 </code></pre>
</div>
</div>
<p><strong>Explicación:</strong></p>
<ul>
<li><p>El kernel RBF es una función que permite realizar clasificación en espacios de características no lineales.</p></li>
<li><p>Hiperparámetro sigma: En este caso, se utilizó un valor de sigma igual a 0.0405, que implica que los puntos de datos cercanos tienen una influencia más fuerte en la clasificación.</p></li>
<li><p>Número de vectores de soporte: En este caso, se encontraron 107 vectores de soporte durante el entrenamiento del modelo. Estos vectores de soporte son los puntos clave para la clasificación y se utilizan para definir el hiperplano de separación en la máquina de vectores.</p></li>
<li><p>Valor de la función objetivo: El valor de la función fue de -47,33, lo que indica que se obtuvo un buen ajuste del modelo a los datos de entrenamiento.</p></li>
<li><p>Error de entrenamiento: El error de entrenamiento fue bajo, es decir que el 1.50075% de puntos de datos de entrenamiento fueron clasificados incorrectamente por el modelo.</p></li>
</ul>
</section>
<section id="evaluación-del-rendimiento-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="evaluación-del-rendimiento-del-modelo">4. Evaluación del rendimiento del modelo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>prediction.linear<span class="ot">&lt;-</span><span class="fu">predict</span>(clasifier.lineal,prueba.data)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>res.linear<span class="ot">&lt;-</span><span class="fu">table</span>(prediction.linear, prueba.data<span class="sc">$</span>diagnostico)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>prediction.gauss<span class="ot">&lt;-</span><span class="fu">predict</span>(clasifier.gauss,prueba.data)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>res.gauss<span class="ot">&lt;-</span><span class="fu">table</span>(prediction.gauss,prueba.data<span class="sc">$</span>diagnostico)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Explicación:</p>
<p>El código realiza la predicción utilizando los clasificadores SVM lineal y SVM gaussiano en el conjunto de datos de prueba. Luego, se crea una tabla de contingencia para evaluar la precisión de las predicciones realizadas por cada clasificador. Las tablas de contingencia (<strong><code>res.linear</code></strong> y <strong><code>res.gauss</code></strong>) permiten comparar las predicciones con las etiquetas de clase reales y analizar la precisión de los clasificadores en la clasificación de los datos de prueba.</p>
<p><strong>DE AQUÍ PARA ABAJO YA ME SALIÓ ERROR :c.</strong></p>
<p><strong>Ahí ve cómo le arreglas :)</strong></p>
</section>
<section id="opcional-validación-cruzada" class="level2">
<h2 class="anchored" data-anchor-id="opcional-validación-cruzada">Opcional: Validación cruzada</h2>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>